title: "ASSET | ARK: Survival Server Environment Toolkit"
description: "The all-in-one toolkit for ARK: Survival Ascended server management."
theme: minima
logo: /assets/asset-logo.svg
show_downloads: true


nav:
  - title: "Home"
    url: /
  - title: "Documentation"
    url: /docs
  - title: "Download"
    url: https://github.com/yourorg/asset/releases
  - title: "GitHub"
    url: https://github.com/yourorg/asset

sass:
  style: compressed

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
