title: "ASSET | ARK: Survival Server Environment Toolkit"
description: "The all-in-one toolkit for ARK: Survival Ascended server management."

show_downloads: true

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: auto  # 'auto' enables automatic switching; use 'dark' for always-dark

nav:
  - title: "Home"
    url: /
  - title: "Documentation"
    url: /docs
  - title: "Download"
    url: https://github.com/yourorg/asset/releases
  - title: "GitHub"
    url: https://github.com/yourorg/asset

sass:
  style: compressed

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
